# Try 1

```{r}
set.seed(1)
library(tidyverse)
library(gganimate)
df <- tibble(
    x = rnorm(100)
    , y = rnorm(100)
    , size = rep(c(2, 3, 4, 5), 25)
    , cl = sample(c("a", "b"), 100, T)
    , time = c(1, rep(1:3, 33)) #|> lubridate::year()
) |> 
    arrange(time)


p2 <- 
    df |> 
    ggplot() + 
    aes(x, y, size = size, color = cl) +
    geom_point() +
    scale_size(range = c(5, 12)) +
    theme_minimal() +
    #transition_time()
    transition_layers(layer_length = 3, transition_length = 3) +
    #enter_fade() +
    transition_time(time) +
    #enter_grow() +
    exit_shrink()
p2


#kanimate(p2, renderer = gifski_renderer("sa.gif")) 
```
```{r}
a <- ggplot(df,
aes(x, y, size = size, color = cl)) +
geom_point(alpha = .6) +
    scale_size(range = c(3, 8))

a +
    
    enter_fade() + 
    transition_states(time, transition_length = 2, state_length = 2) +
    #transition_states(layer_length = 3, transition_length = 3) +
    #transition_manual(time, cumulative = F) +
    enter_grow() +
    exit_shrink() +
    exit_fade()
```


```{r}
a + facet_wrap(~time, ncol = 2)
```

