```{r}
librarian::shelf(
  arules
  , tidyverse
  , arulesViz
)
```


```{r}
data("Groceries") 

api <- Groceries
api 
```


```{r}
rules <- apriori(api, parameter = list(supp = 0.01, conf = 0.2))
```

```{r}
inspect(rules[1:10])
```

```{r}
api <- read_csv("https://raw.githubusercontent.com/nupur1492/RProjects/master/MarketBasketAnalysis/Groceries_dataset.csv") |> 
  janitor::clean_names()
```


```{r}
api
```


```{r}
api_arrang <- arrange(api, member_number)
api_arrang
```


```{r}
if(sessionInfo()['basePkgs']=="dplyr" | sessionInfo()['otherPkgs']=="dplyr"){
  detach(package:dplyr, unload=TRUE)
}
library(plyr)
```

```{r}
api_unite <- ddply(api, c("member_number", "date"), function(.df) paste(.df$item_description, collapse = ","))
```


```{r}
api_unite$member_number <- api_unite$date <- NULL
```

```{r}
colnames(api_unite) <- c("itemList")
write.csv(api_unite, here::here("d3", "rule.csv"))
```


```{r}
library(arules)
```

```{r}
txn <-  read.transactions(file=here::here("d3", "rule.csv"), rm.duplicates= TRUE, format="basket",sep=",",cols=1)
```

```{r}
txn
```

```{r}
txn@itemInfo$labels <- gsub("\"","",txn@itemInfo$labels)
```

```{r}
basket_rules <- apriori(txn,parameter = list(sup = 0.01, conf = 0.5,target="rules"))
```

```{r}
if(sessionInfo()['basePkgs']=="tm" | sessionInfo()['otherPkgs']=="tm"){
    detach(package:tm, unload=TRUE)
  }

inspect(basket_rules)

#Alternative to inspect() is to convert rules to a dataframe and then use View()
df_basket <- as(basket_rules,"data.frame")
View(df_basket)
```

```{r}
library(arulesViz)
plot(basket_rules)
plot(basket_rules, method = "grouped", control = list(k = 5))
plot(basket_rules, method="graph", control=list(type="items"))
plot(basket_rules, method="paracoord",  control=list(alpha=.5, reorder=TRUE))
plot(basket_rules,measure=c("support","lift"),shading="confidence",interactive=T)
```

```{r}
d3 <- read.csv("https://raw.githubusercontent.com/maratonadev/desafio-3-2021/main/assets/data/InvestmentBankCDE.csv") |>   dplyr::mutate_all(as.numeric) |> 
  select(!ID)

d3
d3_m <- as.matrix(d3)
```

```{r}
first <- arules::apriori(d3_m)

```

```{r}
library(arules)
z <- as(first, "data.frame")
z |> 
  arrange(desc(confidence))
```

```{r}
rules <- sort(first, decreasing = T, by = 'confidence')
is.subset(rules@lhs, d3_m[3])
arules::predict(rules, d3_m[1:10])
```



```{r}
library(arulesViz)
plot(first)
plot(first, method = "grouped", control = list(k = 5))
plot(first, method="graph", control=list(type="items"))
plot(first, method="paracoord",  control=list(alpha=.5, reorder=TRUE))
plot(first,measure=c("support","lift"),shading="confidence",interactive=T)
```

